services:
  - type: web
    name: aloy-ecommerce
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ecommerce-app.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080 